import 'dart:io';

import 'package:flutter/services.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

import '../core/constants/export_constants.dart';
import '../models/history_model.dart';
import 'base_repository.dart';

/// Handles PDF export, sharing, and file access.
/// Ready for backend upload, cloud sync, and email delivery.
class PdfExportRepository extends BaseRepository {
  PdfExportRepository({
    required super.apiService,
    required super.storageService,
  });

  pw.Font? _regularFont;
  pw.Font? _boldFont;
  pw.Font? _latinRegularFont;
  pw.Font? _latinBoldFont;

  Future<File?> exportDocumentToPdf(
    HistoryModel document, {
    required String status,
  }) async {
    final bytes = await generatePdfBytes(document, status: status);
    if (bytes == null) return null;

    try {
      final directory = await _ensurePdfExportsDirectory();
      final title = documentTitleOf(document);
      final fileName = _buildUniquePdfFileName(title);
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    } catch (_) {
      return null;
    }
  }

  /// Human-readable title derived from OCR text (same as PDF report title).
  String documentTitleOf(HistoryModel document) {
    return _documentTitle(document.extractedText);
  }

  /// Builds a PDF report in memory using bundled Arabic fonts (offline).
  Future<Uint8List?> generatePdfBytes(
    HistoryModel document, {
    required String status,
  }) async {
    try {
      final regularFont = await _getRegularFont();
      final boldFont = await _getBoldFont();
      final latinRegularFont = _getLatinRegularFont();
      final latinBoldFont = _getLatinBoldFont();
      final imageBytes = await _loadImageBytes(document.imagePath);
      final confidencePercent =
          (document.confidence * 100).clamp(0, 100).toStringAsFixed(0);
      final savedDate = _formatDateTime(document.createdAt);
      final stats = _computeTextStats(document.extractedText);
      final documentTitle = _documentTitle(document.extractedText);

      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 36),
            theme: pw.ThemeData.withFont(
              base: regularFont,
              bold: boldFont,
              fontFallback: [latinRegularFont, latinBoldFont],
            ),
          ),
          footer: (context) => pw.Container(
            alignment: pw.Alignment.centerRight,
            child: pw.Text(
              'Generated by ${ExportConstants.appExportTitle} - '
              '${_formatDateTime(DateTime.now())}',
              style: _regularTextStyle(
                regularFont,
                latinRegularFont,
                fontSize: 9,
                color: PdfColors.grey600,
              ),
            ),
          ),
          build: (context) => [
            _buildHeader(boldFont, regularFont, latinRegularFont, latinBoldFont),
            pw.SizedBox(height: 28),
            _buildSectionTitle(
              'Document Information',
              boldFont,
              latinBoldFont,
            ),
            pw.SizedBox(height: 12),
            _buildInfoCard(
              regularFont: regularFont,
              boldFont: boldFont,
              latinRegularFont: latinRegularFont,
              latinBoldFont: latinBoldFont,
              rows: [
                _InfoRow('Document Title', documentTitle),
                _InfoRow('Document ID', document.id),
                _InfoRow('Created Date', savedDate),
                _InfoRow('Confidence Score', '$confidencePercent%'),
                _InfoRow('Status', status),
              ],
            ),
            pw.SizedBox(height: 24),
            _buildSectionTitle('Statistics', boldFont, latinBoldFont),
            pw.SizedBox(height: 12),
            _buildInfoCard(
              regularFont: regularFont,
              boldFont: boldFont,
              latinRegularFont: latinRegularFont,
              latinBoldFont: latinBoldFont,
              rows: [
                _InfoRow('Characters', stats.characters.toString()),
                _InfoRow('Words', stats.words.toString()),
                _InfoRow('Lines', stats.lines.toString()),
              ],
            ),
            pw.SizedBox(height: 24),
            if (imageBytes != null) ...[
              _buildSectionTitle('Original Image', boldFont, latinBoldFont),
              pw.SizedBox(height: 12),
              pw.Center(
                child: pw.Container(
                  padding: const pw.EdgeInsets.all(8),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: pw.BorderRadius.circular(12),
                  ),
                  child: pw.ClipRRect(
                    horizontalRadius: 8,
                    verticalRadius: 8,
                    child: pw.Image(
                      pw.MemoryImage(imageBytes),
                      fit: pw.BoxFit.contain,
                      height: 280,
                    ),
                  ),
                ),
              ),
              pw.SizedBox(height: 24),
            ],
            _buildSectionTitle('Extracted Text', boldFont, latinBoldFont),
            pw.SizedBox(height: 12),
            _buildExtractedTextSection(
              document.extractedText,
              regularFont,
              latinRegularFont,
            ),
          ],
        ),
      );

      return pdf.save();
    } catch (_) {
      return null;
    }
  }

  /// Writes an offline Arabic PDF test report for font and RTL verification.
  Future<File?> generateArabicTestReport() async {
    const arabicText =
        'مرحباً بكم في تطبيق مكتوب.\n\n'
        'هذا نص تجريبي مستخرج من الصورة باستخدام تقنية التعرف الضوئي على الحروف.\n'
        'يمكنك تعديل هذا النص بالضغط على زر "تعديل النص".';

    final document = HistoryModel(
      id: 'arabic_pdf_test',
      imagePath: '',
      extractedText: arabicText,
      confidence: 0.95,
      createdAt: DateTime.now(),
    );

    final bytes = await _generateArabicTestPdfBytes(
      document: document,
      status: 'تمت المعالجة، تم التحرير',
    );
    if (bytes == null) return null;

    try {
      final directory = await _ensureExportsDirectory();
      final file = File(
        '${directory.path}/${ExportConstants.arabicTestReportFileName}',
      );
      await file.writeAsBytes(bytes);
      return file;
    } catch (_) {
      return null;
    }
  }

  Future<Uint8List?> _generateArabicTestPdfBytes({
    required HistoryModel document,
    required String status,
  }) async {
    try {
      final regularFont = await _getRegularFont();
      final boldFont = await _getBoldFont();
      final latinRegularFont = _getLatinRegularFont();
      final latinBoldFont = _getLatinBoldFont();
      final stats = _computeTextStats(document.extractedText);
      final documentTitle = _documentTitle(document.extractedText);
      final savedDate = _formatDateTime(document.createdAt);
      final confidencePercent =
          (document.confidence * 100).clamp(0, 100).toStringAsFixed(0);

      final pdf = pw.Document();

      pdf.addPage(
        pw.MultiPage(
          pageTheme: pw.PageTheme(
            margin: const pw.EdgeInsets.symmetric(horizontal: 40, vertical: 36),
            theme: pw.ThemeData.withFont(
              base: regularFont,
              bold: boldFont,
              fontFallback: [latinRegularFont, latinBoldFont],
            ),
          ),
          footer: (context) => pw.Directionality(
            textDirection: pw.TextDirection.rtl,
            child: pw.Container(
              alignment: pw.Alignment.centerRight,
              child: pw.Text(
                'تم إنشاؤه بواسطة مكتوب - '
                '${_formatDateTime(DateTime.now())}',
                style: _regularTextStyle(
                  regularFont,
                  latinRegularFont,
                  fontSize: 9,
                  color: PdfColors.grey600,
                ),
                textAlign: pw.TextAlign.right,
              ),
            ),
          ),
          build: (context) => [
            _buildArabicHeader(boldFont, regularFont),
            pw.SizedBox(height: 28),
            _buildArabicSectionTitle('معلومات المستند', boldFont),
            pw.SizedBox(height: 12),
            _buildInfoCard(
              regularFont: regularFont,
              boldFont: boldFont,
              latinRegularFont: latinRegularFont,
              latinBoldFont: latinBoldFont,
              rows: [
                _InfoRow('عنوان المستند', documentTitle),
                _InfoRow('معرف المستند', document.id),
                _InfoRow('تاريخ الإنشاء', savedDate),
                _InfoRow('نسبة الثقة', '$confidencePercent%'),
                _InfoRow('الحالة', status),
              ],
            ),
            pw.SizedBox(height: 24),
            _buildArabicSectionTitle('إحصائيات النص', boldFont),
            pw.SizedBox(height: 12),
            _buildInfoCard(
              regularFont: regularFont,
              boldFont: boldFont,
              latinRegularFont: latinRegularFont,
              latinBoldFont: latinBoldFont,
              rows: [
                _InfoRow('عدد الأحرف', stats.characters.toString()),
                _InfoRow('عدد الكلمات', stats.words.toString()),
                _InfoRow('عدد الأسطر', stats.lines.toString()),
              ],
            ),
            pw.SizedBox(height: 24),
            _buildArabicSectionTitle('النص المستخرج', boldFont),
            pw.SizedBox(height: 12),
            _buildExtractedTextSection(
              document.extractedText,
              regularFont,
              latinRegularFont,
            ),
          ],
        ),
      );

      return pdf.save();
    } catch (_) {
      return null;
    }
  }

  Future<void> shareExportedFile(File file) async {
    if (!await file.exists()) return;

    await Share.shareXFiles(
      [XFile(file.path, mimeType: 'application/pdf')],
      subject: '${ExportConstants.appExportTitle} Report',
      text: 'Exported OCR document PDF',
    );
  }

  Future<void> openExportedFile(File file) async {
    if (!await file.exists()) return;

    await OpenFilex.open(
      file.path,
      type: 'application/pdf',
    );
  }

  Future<void> uploadToBackend(File file) async {
    // Placeholder — Dio multipart upload when backend is ready
  }

  Future<void> syncToCloud(File file) async {
    // Placeholder — cloud sync integration
  }

  Future<void> emailPdf(File file, {required String recipient}) async {
    // Placeholder — email delivery integration
  }

  pw.Widget _buildHeader(
    pw.Font boldFont,
    pw.Font regularFont,
    pw.Font latinRegularFont,
    pw.Font latinBoldFont,
  ) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.symmetric(vertical: 20, horizontal: 16),
      decoration: pw.BoxDecoration(
        color: PdfColor.fromHex('#E8F0EA'),
        borderRadius: pw.BorderRadius.circular(12),
        border: pw.Border.all(color: PdfColor.fromHex('#14532D'), width: 0.5),
      ),
      child: pw.Column(
        children: [
          pw.Text(
            ExportConstants.appExportTitle,
            style: _boldTextStyle(
              boldFont,
              latinBoldFont,
              fontSize: 26,
              color: PdfColor.fromHex('#14532D'),
            ),
            textAlign: pw.TextAlign.center,
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            'OCR Document Report',
            style: _regularTextStyle(
              regularFont,
              latinRegularFont,
              fontSize: 12,
              color: PdfColors.grey700,
            ),
            textAlign: pw.TextAlign.center,
          ),
        ],
      ),
    );
  }

  pw.Widget _buildArabicHeader(pw.Font boldFont, pw.Font regularFont) {
    return pw.Directionality(
      textDirection: pw.TextDirection.rtl,
      child: pw.Container(
        width: double.infinity,
        padding: const pw.EdgeInsets.symmetric(vertical: 20, horizontal: 16),
        decoration: pw.BoxDecoration(
          color: PdfColor.fromHex('#E8F0EA'),
          borderRadius: pw.BorderRadius.circular(12),
          border: pw.Border.all(color: PdfColor.fromHex('#14532D'), width: 0.5),
        ),
        child: pw.Column(
          children: [
            pw.Text(
              'مكتوب',
              style: _boldTextStyle(
                boldFont,
                _getLatinBoldFont(),
                fontSize: 26,
                color: PdfColor.fromHex('#14532D'),
              ),
              textAlign: pw.TextAlign.center,
            ),
            pw.SizedBox(height: 6),
            pw.Text(
              'تقرير مستند OCR',
              style: _regularTextStyle(
                regularFont,
                _getLatinRegularFont(),
                fontSize: 12,
                color: PdfColors.grey700,
              ),
              textAlign: pw.TextAlign.center,
            ),
          ],
        ),
      ),
    );
  }

  pw.Widget _buildSectionTitle(
    String title,
    pw.Font boldFont,
    pw.Font latinBoldFont,
  ) {
    return pw.Text(
      title,
      style: _boldTextStyle(
        boldFont,
        latinBoldFont,
        fontSize: 16,
        color: PdfColors.grey900,
      ),
    );
  }

  pw.Widget _buildArabicSectionTitle(String title, pw.Font boldFont) {
    return pw.Directionality(
      textDirection: pw.TextDirection.rtl,
      child: pw.Align(
        alignment: pw.Alignment.centerRight,
        child: pw.Text(
          title,
          style: _boldTextStyle(
            boldFont,
            _getLatinBoldFont(),
            fontSize: 16,
            color: PdfColors.grey900,
          ),
          textAlign: pw.TextAlign.right,
        ),
      ),
    );
  }

  pw.Widget _buildInfoCard({
    required pw.Font regularFont,
    required pw.Font boldFont,
    required pw.Font latinRegularFont,
    required pw.Font latinBoldFont,
    required List<_InfoRow> rows,
  }) {
    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(12),
        color: PdfColors.grey50,
      ),
      child: pw.Column(
        children: [
          for (var i = 0; i < rows.length; i++) ...[
            pw.Row(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.SizedBox(
                  width: 130,
                  child: _buildLabelText(
                    rows[i].label,
                    boldFont,
                    latinBoldFont,
                  ),
                ),
                pw.Expanded(
                  child: _buildValueText(
                    rows[i].value,
                    regularFont,
                    latinRegularFont,
                  ),
                ),
              ],
            ),
            if (i < rows.length - 1) pw.SizedBox(height: 10),
          ],
        ],
      ),
    );
  }

  pw.Widget _buildLabelText(
    String text,
    pw.Font font,
    pw.Font latinFont,
  ) {
    final isRtl = _containsArabic(text);
    final child = pw.Text(
      text,
      style: _boldTextStyle(
        font,
        latinFont,
        fontSize: 11,
        color: PdfColors.grey700,
      ),
      textAlign: isRtl ? pw.TextAlign.right : pw.TextAlign.left,
    );

    if (!isRtl) return child;

    return pw.Directionality(
      textDirection: pw.TextDirection.rtl,
      child: child,
    );
  }

  pw.Widget _buildValueText(
    String text,
    pw.Font font,
    pw.Font latinFont,
  ) {
    final isRtl = _containsArabic(text);
    final child = pw.Text(
      text,
      style: _regularTextStyle(
        font,
        latinFont,
        fontSize: 11,
        color: PdfColors.grey900,
      ),
      textAlign: isRtl ? pw.TextAlign.right : pw.TextAlign.left,
    );

    if (!isRtl) return child;

    return pw.Directionality(
      textDirection: pw.TextDirection.rtl,
      child: child,
    );
  }

  pw.Widget _buildExtractedTextSection(
    String text,
    pw.Font regularFont,
    pw.Font latinRegularFont,
  ) {
    final displayText = text.trim().isEmpty ? 'No text extracted.' : text;
    final isRtl = _containsArabic(displayText);

    final content = pw.Text(
      displayText,
      style: _regularTextStyle(
        regularFont,
        latinRegularFont,
        fontSize: 14,
        lineSpacing: 8,
      ),
      textAlign: isRtl ? pw.TextAlign.right : pw.TextAlign.left,
    );

    return pw.Container(
      width: double.infinity,
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(12),
      ),
      child: isRtl
          ? pw.Directionality(
              textDirection: pw.TextDirection.rtl,
              child: content,
            )
          : content,
    );
  }

  pw.TextStyle _regularTextStyle(
    pw.Font font,
    pw.Font latinFont, {
    required double fontSize,
    PdfColor? color,
    double? lineSpacing,
  }) {
    return pw.TextStyle(
      font: font,
      fontFallback: [latinFont],
      fontSize: fontSize,
      color: color,
      lineSpacing: lineSpacing,
    );
  }

  pw.TextStyle _boldTextStyle(
    pw.Font font,
    pw.Font latinFont, {
    required double fontSize,
    PdfColor? color,
  }) {
    return pw.TextStyle(
      font: font,
      fontFallback: [latinFont],
      fontSize: fontSize,
      color: color,
      fontWeight: pw.FontWeight.bold,
    );
  }

  Future<pw.Font> _getRegularFont() async {
    _regularFont ??= pw.Font.ttf(
      (await rootBundle.load(ExportConstants.arabicRegularFontAsset))
          .buffer
          .asByteData(),
    );
    return _regularFont!;
  }

  Future<pw.Font> _getBoldFont() async {
    _boldFont ??= pw.Font.ttf(
      (await rootBundle.load(ExportConstants.arabicBoldFontAsset))
          .buffer
          .asByteData(),
    );
    return _boldFont!;
  }

  pw.Font _getLatinRegularFont() {
    return _latinRegularFont ??= pw.Font.helvetica();
  }

  pw.Font _getLatinBoldFont() {
    return _latinBoldFont ??= pw.Font.helveticaBold();
  }

  Future<Uint8List?> _loadImageBytes(String path) async {
    if (path.isEmpty) return null;

    final file = File(path);
    if (!await file.exists()) return null;

    return file.readAsBytes();
  }

  Future<Directory> _ensureExportsDirectory() async {
    final baseDirectory = await getApplicationDocumentsDirectory();
    final exportsDirectory = Directory(
      '${baseDirectory.path}/${ExportConstants.exportsFolderName}',
    );

    if (!await exportsDirectory.exists()) {
      await exportsDirectory.create(recursive: true);
    }

    return exportsDirectory;
  }

  Future<Directory> _ensurePdfExportsDirectory() async {
    final baseDirectory = await _ensureExportsDirectory();
    final pdfDirectory = Directory(
      '${baseDirectory.path}/${ExportConstants.pdfExportsSubfolder}',
    );

    if (!await pdfDirectory.exists()) {
      await pdfDirectory.create(recursive: true);
    }

    return pdfDirectory;
  }

  String _buildUniquePdfFileName(String title) {
    final base = _sanitizeFileName(title);
    final stamp = DateTime.now().millisecondsSinceEpoch;
    return '${base}_$stamp${ExportConstants.pdfFileExtension}';
  }

  String _sanitizeFileName(String input) {
    var name = input.trim();
    if (name.isEmpty) name = 'document';

    name = name.replaceAll(RegExp(r'[<>:"/\\|?*\x00-\x1F]'), '_');
    name = name.replaceAll(RegExp(r'\s+'), ' ').trim();
    if (name.endsWith('.')) {
      name = name.substring(0, name.length - 1).trim();
    }

    const maxLength = 60;
    if (name.length > maxLength) {
      name = name.substring(0, maxLength).trim();
    }

    return name.isEmpty ? 'document' : name;
  }

  String _formatDateTime(DateTime dateTime) {
    final day = dateTime.day.toString().padLeft(2, '0');
    final month = dateTime.month.toString().padLeft(2, '0');
    final year = dateTime.year;
    final hour = dateTime.hour.toString().padLeft(2, '0');
    final minute = dateTime.minute.toString().padLeft(2, '0');
    return '$day/$month/$year - $hour:$minute';
  }

  String _documentTitle(String extractedText) {
    final trimmed = extractedText.trim();
    if (trimmed.isEmpty) return 'Untitled Document';

    final firstLine = trimmed.split('\n').first.trim();
    if (firstLine.isEmpty) return 'Untitled Document';

    const maxLength = 80;
    if (firstLine.length <= maxLength) return firstLine;
    return '${firstLine.substring(0, maxLength)}...';
  }

  _TextStats _computeTextStats(String text) {
    final trimmed = text.trim();
    final characters = text.length;
    final words = trimmed.isEmpty
        ? 0
        : trimmed.split(RegExp(r'\s+')).where((word) => word.isNotEmpty).length;
    final lines = text.isEmpty ? 0 : text.split('\n').length;

    return _TextStats(
      characters: characters,
      words: words,
      lines: lines,
    );
  }

  bool _containsArabic(String text) {
    return RegExp(r'[\u0600-\u06FF]').hasMatch(text);
  }
}

class _InfoRow {
  const _InfoRow(this.label, this.value);

  final String label;
  final String value;
}

class _TextStats {
  const _TextStats({
    required this.characters,
    required this.words,
    required this.lines,
  });

  final int characters;
  final int words;
  final int lines;
}
