import 'dart:io';

import 'package:docx_creator/docx_creator.dart';
import 'package:flutter/services.dart';
import 'package:open_filex/open_filex.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

import '../core/constants/export_constants.dart';
import '../models/history_model.dart';
import 'base_repository.dart';

/// Handles Word (.docx) export, sharing, and file access.
/// Ready for backend upload and cloud sync.
class WordExportRepository extends BaseRepository {
  WordExportRepository({
    required super.apiService,
    required super.storageService,
  });

  Future<File?> exportDocumentToWord(HistoryModel document) async {
    final bytes = await generateDocxBytes(document);
    if (bytes == null) return null;

    try {
      final directory = await _ensureExportsDirectory();
      final fileName =
          '${ExportConstants.wordFilePrefix}${_sanitizeId(document.id)}${ExportConstants.wordFileExtension}';
      final file = File('${directory.path}/$fileName');
      await file.writeAsBytes(bytes);
      return file;
    } catch (_) {
      return null;
    }
  }

  Future<List<int>?> generateDocxBytes(HistoryModel document) async {
    try {
      final regularFontBytes =
          (await rootBundle.load(ExportConstants.arabicRegularFontAsset))
              .buffer
              .asUint8List();
      final boldFontBytes =
          (await rootBundle.load(ExportConstants.arabicBoldFontAsset))
              .buffer
              .asUint8List();

      final confidencePercent =
          (document.confidence * 100).clamp(0, 100).toStringAsFixed(0);
      final savedDate = _formatDateTime(document.createdAt);
      final documentTitle = _documentTitle(document.extractedText);

      final builder = docx()
        ..addFont(ExportConstants.wordFontRegularFamily, regularFontBytes)
        ..addFont(ExportConstants.wordFontBoldFamily, boldFontBytes)
        ..add(_spacerParagraph())
        ..add(
          _paragraph(
            ExportConstants.appExportTitle,
            bold: true,
            fontSizeHalfPoints: 52,
            align: 'center',
          ),
        )
        ..add(
          _paragraph(
            'OCR Document Report',
            fontSizeHalfPoints: 24,
            align: 'center',
          ),
        )
        ..add(_spacerParagraph())
        ..add(
          _paragraph(
            'Document Information',
            bold: true,
            fontSizeHalfPoints: 32,
          ),
        )
        ..add(_spacerParagraph())
        ..add(_infoLine('Document Title', documentTitle))
        ..add(_infoLine('Document ID', document.id))
        ..add(_infoLine('Created Date', savedDate))
        ..add(_infoLine('Confidence Score', '$confidencePercent%'))
        ..add(_spacerParagraph())
        ..add(
          _paragraph(
            'Extracted Text',
            bold: true,
            fontSizeHalfPoints: 32,
          ),
        )
        ..add(_spacerParagraph());

      for (final paragraph in _extractedTextParagraphs(document.extractedText)) {
        builder.add(paragraph);
      }

      builder.add(
        _paragraph(
          'Generated by ${ExportConstants.appExportTitle} - '
          '${_formatDateTime(DateTime.now())}',
          fontSizeHalfPoints: 18,
          align: 'right',
        ),
      );

      final doc = builder.build();
      return DocxExporter().exportToBytes(doc);
    } catch (_) {
      return null;
    }
  }

  Future<void> shareExportedFile(File file) async {
    if (!await file.exists()) return;

    await Share.shareXFiles(
      [
        XFile(
          file.path,
          mimeType:
              'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        ),
      ],
      subject: '${ExportConstants.appExportTitle} Report',
      text: 'Exported OCR document Word file',
    );
  }

  Future<void> openExportedFile(File file) async {
    if (!await file.exists()) return;

    await OpenFilex.open(
      file.path,
      type:
          'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    );
  }

  Future<void> uploadToBackend(File file) async {
    // Placeholder — Dio multipart upload when backend is ready
  }

  Future<void> syncToCloud(File file) async {
    // Placeholder — cloud sync integration
  }

  DocxRawXml _infoLine(String label, String value) {
    final rtl = _containsArabic(value);
    final escapedLabel = _escapeXml(label);
    final escapedValue = _escapeXml(value);
    final valueRun = rtl
        ? '''
    <w:r>
      <w:rPr>
        <w:rtl/>
        <w:rFonts w:ascii="${ExportConstants.wordFontRegularFamily}" w:hAnsi="${ExportConstants.wordFontRegularFamily}" w:cs="${ExportConstants.wordFontRegularFamily}"/>
        <w:sz w:val="22"/>
        <w:szCs w:val="22"/>
      </w:rPr>
      <w:t xml:space="preserve">$escapedValue</w:t>
    </w:r>'''
        : '''
    <w:r>
      <w:rPr>
        <w:rFonts w:ascii="${ExportConstants.wordFontRegularFamily}" w:hAnsi="${ExportConstants.wordFontRegularFamily}" w:cs="${ExportConstants.wordFontRegularFamily}"/>
        <w:sz w:val="22"/>
        <w:szCs w:val="22"/>
      </w:rPr>
      <w:t xml:space="preserve">$escapedValue</w:t>
    </w:r>''';

    return DocxRawXml('''
<w:p>
  <w:pPr>
    <w:jc w:val="${rtl ? 'right' : 'left'}"/>
    ${rtl ? '<w:bidi/>' : ''}
    <w:spacing w:after="80"/>
  </w:pPr>
  <w:r>
    <w:rPr>
      <w:b/>
      <w:bCs/>
      <w:rFonts w:ascii="${ExportConstants.wordFontBoldFamily}" w:hAnsi="${ExportConstants.wordFontBoldFamily}" w:cs="${ExportConstants.wordFontBoldFamily}"/>
      <w:sz w:val="22"/>
      <w:szCs w:val="22"/>
    </w:rPr>
    <w:t xml:space="preserve">$escapedLabel: </w:t>
  </w:r>
  $valueRun
</w:p>''');
  }

  DocxRawXml _paragraph(
    String text, {
    bool bold = false,
    int fontSizeHalfPoints = 22,
    String align = 'left',
  }) {
    final rtl = _containsArabic(text);
    final font = bold
        ? ExportConstants.wordFontBoldFamily
        : ExportConstants.wordFontRegularFamily;

    return DocxRawXml('''
<w:p>
  <w:pPr>
    <w:jc w:val="${rtl ? 'right' : align}"/>
    ${rtl ? '<w:bidi/>' : ''}
    <w:spacing w:after="120"/>
  </w:pPr>
  <w:r>
    <w:rPr>
      ${rtl ? '<w:rtl/>' : ''}
      <w:rFonts w:ascii="$font" w:hAnsi="$font" w:cs="$font"/>
      <w:sz w:val="$fontSizeHalfPoints"/>
      <w:szCs w:val="$fontSizeHalfPoints"/>
    </w:rPr>
    <w:t xml:space="preserve">${_escapeXml(text)}</w:t>
  </w:r>
</w:p>''');
  }

  List<DocxRawXml> _extractedTextParagraphs(String text) {
    final trimmed = text.trim();
    if (trimmed.isEmpty) {
      return [_paragraph('No text extracted.')];
    }

    return trimmed
        .split('\n')
        .map((line) => _paragraph(line.isEmpty ? ' ' : line))
        .toList();
  }

  DocxRawXml _spacerParagraph() {
    return DocxRawXml('''
<w:p>
  <w:pPr>
    <w:spacing w:after="120"/>
  </w:pPr>
</w:p>''');
  }

  Future<Directory> _ensureExportsDirectory() async {
    final baseDirectory = await getApplicationDocumentsDirectory();
    final exportsDirectory = Directory(
      '${baseDirectory.path}/${ExportConstants.exportsFolderName}/${ExportConstants.wordExportsSubfolder}',
    );

    if (!await exportsDirectory.exists()) {
      await exportsDirectory.create(recursive: true);
    }

    return exportsDirectory;
  }

  String _sanitizeId(String id) {
    final sanitized = id.replaceAll(RegExp(r'[^\w\-]'), '_');
    return sanitized.isEmpty ? 'unknown' : sanitized;
  }

  String _formatDateTime(DateTime dateTime) {
    final day = dateTime.day.toString().padLeft(2, '0');
    final month = dateTime.month.toString().padLeft(2, '0');
    final year = dateTime.year;
    final hour = dateTime.hour.toString().padLeft(2, '0');
    final minute = dateTime.minute.toString().padLeft(2, '0');
    return '$day/$month/$year - $hour:$minute';
  }

  String documentTitleOf(HistoryModel document) {
    return _documentTitle(document.extractedText);
  }

  String _documentTitle(String extractedText) {
    final trimmed = extractedText.trim();
    if (trimmed.isEmpty) return 'Untitled Document';

    final firstLine = trimmed.split('\n').first.trim();
    if (firstLine.isEmpty) return 'Untitled Document';

    const maxLength = 80;
    if (firstLine.length <= maxLength) return firstLine;
    return '${firstLine.substring(0, maxLength)}...';
  }

  bool _containsArabic(String text) {
    return RegExp(r'[\u0600-\u06FF]').hasMatch(text);
  }

  String _escapeXml(String text) {
    return text
        .replaceAll('&', '&amp;')
        .replaceAll('<', '&lt;')
        .replaceAll('>', '&gt;')
        .replaceAll('"', '&quot;')
        .replaceAll("'", '&apos;');
  }
}
