org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true

android.useAndroidX=true
android.enableJetifier=false

android.nonTransitiveRClass=true
android.defaults.buildfeatures.buildconfig=false
android.defaults.buildfeatures.aidl=false
android.defaults.buildfeatures.renderScript=false
android.defaults.buildfeatures.resValues=false
android.defaults.buildfeatures.shaders=false

android.lint.checkReleaseBuilds=false
android.lint.abortOnError=false

kotlin.incremental=true
kotlin.code.style=official
